### ISSUE TITLE
Web interface: Alternative repository title and description

### ISSUE THREAD

**Issue by ghost** [GreenDelta/lca-collaboration-server-log#12]
Currently, when opening a repository in the web browser, the repository's group and its name are displayed separated by a _/_. Since there are some restrictions to naming a _group_ and _repository_ (e.g. no spaces), sometimes this does not look very nice. It would be nice if an alternative title could be displayed e.g. "openLCA LCIA methods for EN15804" instead of  "openLCA_LCIA_methods/EN15804". Maybe this could even be supplemented with a short description (e.g. max 1000 characters) in which normal formatting is allowed.

**Comment by SebastianGreve-GreenDelta** [comment]
This is now part of the current 1.3.0 release (labels and descriptions for group and repositories, as well as more metadata)
