### ISSUE TITLE
Access public repositories via openLCA without being member of the repository

### ISSUE THREAD

**Issue by DonMeadows** [GreenDelta/lca-collaboration-server-log#14]
Currently, non-members can only access public repositories via the web interface of the LCA CS. It would be nice if public repositories are also accessible via openLCA even for users who are not a member of a repository. Maybe simply via a link: https://github.com/GreenDelta/lca-collaboration-server-log/issues/13

**Comment by sebastian-greve** [comment]
Public repositories can be imported from openLCA via the "import from repository" wizard, credentials are optional and are not needed for public repositories
