### ISSUE TITLE
Wrong company URL at imprint webpage

### ISSUE THREAD

**Issue by arturszilagyi** [GreenDelta/lca-collaboration-server-log#7]
I added the website of my company (energia.bme.hu) at adiministration/settings page. At the imprint page ( http://152.66.39.194/lca-collaboration-1.0.0/imprint )however, wrong URL is created by combining my server address with the above mentioned company website (e.x. http://152.66.39.194/lca-collaboration-1.0.0/www.energia.bme.hu)

**Comment by sebastian-greve** [comment]
You need to set http or https scheme in the url (full url)
